### General project setup
general:
  unsafeMode: false
  projectName: 'cloud-cap-s4ems-bp'
  productiveBranch: 'master'

### Step-specific configuration
steps:
  artifactPrepareVersion:
    buildTool: 'mta'
npmExecute:
    dockerImage: 'ppiper/node-browsers:v2'
cloudFoundryDeploy:
  dockerImage: 'ppiper/cf-cli'
  mtaDeployParameters: '-f --version-rule ALL'
mtaBuild:
  mtaBuildTool: "cloudMbt"


### Stage-specific configuration
stages:
  npmAudit:
    auditedAdvisories:
    # high
      - 550  
      - 593
      - 1184
      - 755
      - 1065
      - 1164
      - 1316
      - 1324
      - 1325
    # moderate
      - 535
      - 1300

lint:
ui5BestPractices:
  failThreshold:
    error: 100
    warning: 500
    info: 1000

#  integrationTests:
#    credentials:
#      - alias: 'mySystemAlias'
#        credentialId: 'mySystemCredentialsId'

productionDeployment:
  cfTargets:
    - org: 'EngSrvVal-E2E_missionS4'
      space: 'dev'
      apiEndpoint: 'https://api.cf.eu10.hana.ondemand.com'
      appName: 'myAppName'
      manifest: 'manifest.yml'
      credentialsId: 'global'